### PR TITLE
Remove nyc as a global dependency

### PR DESCRIPTION
**Pull request by roschaefer**
Local installation over global installation, no? :thinking: 

@appinteractive I don't see the difference between `test` and `test:coverage`. On current `develop` branch the two results look like the same.

### CODE REVIEW

**Comment by appinteractive** [comment]
The results yes but did you get the same results in the coverage folder?

The local installation of nyc does not work for me at all.

**Comment by roschaefer** [comment]
OK, so `test:coverage` creates the file `lcov.info` in `coverage/`? That does not work locally on my machine. The tests behave as expected though.

I guess I have to research some more on how to chain scripts in `package.json`. I find the current package.json quite confusing and would like to clean it up a little.

**Comment by appinteractive** [comment]
Yeah we need some cleanup indeed!

**Comment by appinteractive** [comment]
I don't know why but intalling nyc localy always throws this:
grafik
Even in `yarn dev`

**Comment by sebako86** [comment]
@appinteractive just found this: https://github.com/npm/npmlog/issues/48

seems nuking node_modules works for some cases. In others there are dependency conflicts where packages require different versions of gauge where older versions do not have isEnabled as a function.

**Comment by appinteractive** [comment]
@sebako86 funny I just was there and saw your reference (two min before) ^^
Sadly that does not help in my case.

**Comment by appinteractive** [comment]
As we are in the process of upgrading packages for feathers v3 this might solve a he issue.
Am 29. Juni 2018, 14:29 +0200 schrieb Sebo <notifications@github.com>:

**Comment by appinteractive** [comment]
Works for everyone except me so I will merge it and still install it for me globally for now.

**Pull request merged**
